# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.TextField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='size',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
