# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20160917_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='classname',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
